### ISSUE TITLE
Lizenzangabe fehlt

### ISSUE THREAD

**Issue by schildwaechter** [DARIAH-DE/dariah-dockerfiles#1]
https://wiki.de.dariah.eu/pages/viewpage.action?pageId=38080370#Empfehlungenf%C3%BCrForschungsdaten,ToolsundMetadateninderDARIAH-DEInfrastruktur-Lizenzenf%C3%BCrCode

**Comment by jrybicki-jsc** [comment]
do your job mister... somewherelse

**Comment by schildwaechter** [comment]
wunschgemäß an dariah-partner verschickt
